language: go
go:
- '1.5'
env:
  global:
  - GAPICMD_VERSION="0.10.${TRAVIS_BUILD_NUMBER}"
  - secure: APKTTr1QkVB9znJtzR7p6ZKObPzvs8dxNUBWBF0EIoaIWRSofnMIFu9FQwoo1IQ+n+InUO3f8y6nogGFpssQCCoKB9V54cfuaqgBNRsDtf5AmxjlEM2/7Jf6RzG5dquqyBKCmKG5uqiYah9ZFbfaSxChCGwNo1a2eRJBx/Md61RlMtBNbEC8WPkmGnEgvXjlDq9z7nq52bkt5/RVf/6FS88fCsfC1hsPSaIuD+eEkQu56BBZGkroIQfMznCfl2ASPN6IuBW097EysS+kuk8oZsouLZesxs6CNUkwkMH/2QIPUB+xuOqARCm4F16UAs9W54GfjGUeS/uVa3skjq3dv3rByzliiHT9CffJHNnQ7JgM89ttYde4ze1T8maLlxCgOsUtQ20GGNq2FEFKh3Oj3oAFbPEypwDu2hr7QdubgbUMAQM169K4SsjxWnCZuUYyHMKwaFaYut8JZwQl9vox/eJ0pIovGjLoN9kOdv6OvGM8NjcVQG6J3juPSN3Tz/Udi/j6xJV5QBxvAKlsL838o2uvbgxvTvY43JHZxMkXFv5wJAYxb58bzSeHVZcpVvTZpjWnKxFNLfKqk/kP64PaZ7QSFoYzatIXgjWYzlbExUT9MZ5Yh03fQtnO75BCRGO7Hg0gbu8S1np1O4YTGS590Nvh9eYS6TqPegV3KWcMrmA=
  - secure: Skh0xMKFHUi8nSlzP6P8n/iSXnBtNDUxgCEkfORT++0yOljLMrzccKH7KyHU5633GUeDTNISGwdF9bhPln/LFOVVNq3lkm7iL10jDfkOSlRVzvTZhs4Og8M0jX3bi7EznCog5M3ddxrMSZ9OKSRRZnCICMd88dlzHnzOFLo+gud1mMVBbk7ub8IxA5Ig/ld5dhXNNm1ocgOR3WUJ0X0kwEnhMsNh/0o4UW8fhAmbQLePIamADjtRxWf8RPND4Fz5jC6LOqPHerJ368hSpOOAHfusdDMVPFbQKHcc/L6WtvxF97B3/UIHq0YILojtrAWm7Xw7MVzWd2JoHyBFIeNDzwTXCYjL9h/v1AdKCHL8RFp/edhcYFkX8ComEm2cGL/jtR86tH/5zu4ynctgk+vM4rUfl6rv77STJfzriCiolurCqciuAWdnem5RkFUwnlzJZEHUYZuD2JikPr4sKzpY7zbt6R+7mFRSViF+ovyHxcOk5zpVxcah/WApD7Sz0TGpD062P0Nqdzf8gc4fJTDLSVkrf1QqeC3UOkT9GQcaDonw4g2nNpN8ToAehg94sUdQHNJbeKzq5UIvAFWsN5Ie54Njsa2msbbkryuDTAMoejzQPvR006ddJksZGdhDjYYebDpWgBqZptZeKOjJ4HnE+ic0ILSNOHa8/HOb/Fn1zQk=
script:
- go get github.com/mitchellh/gox
- gox -osarch="darwin/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
- gox -osarch="linux/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
- gox -osarch="windows/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
before_deploy:
- git tag ${GAPICMD_VERSION}
- git push --tags "https://${GH_TOKEN}@github.com/gini/gapicmd.git/"
deploy:
  provider: releases
  api_key:
    secure: GHyo+sSc5Y6QVO2cFLkDFw1rwrQnuRJScpX8t1is2Bw3p+ZeAVzz9/6TGPjHGKwDThJC+RhxltQZDTPhFOEUOkuwlgQ/XBC+s62uBxPS2bEo2vYH7liKjAy94v7mZ3vv8wqDfl2z3l/TNM7bm5TvvJuaVLMIdS/Qy+/O5qqqocSMTZJk77H3LHI/MbZeiSRzNpgc5c0OMtVy8xQM3zPwWewWnTfMIoCvrrAQpMRA6VmyD5UUYzHDoiKlibLF8G9vsSAGTXB3lYwCvP+n4KmYxxyJm66pZ+O8lAuAkWPefv26U0O+R3SuO5DOa1QrSb8bOAb+3YDJEtENKzir0pYTuRDuflBz9ORRmJtzWTKAYNhoaPvKNz0f3eo6vNTxaJ2J1eymE9Wy7QjVIw+BcPibbfXaKUh9AODaE01xBneq3rDYoUCXRIerKQ6g8lBWfs5IAesy9cf4udsr1bIpt3xHngsCtGyqnUibBDm+VPZpaSCsrKWnaPBFG8lpavWcmNJYQE9dgVShRfMsJNtNBxMuo0N4EbVJgLMJ0L9o2o6vt9b1mhzsyLPKPkOYAHnKAycVtUBdQn5iLI+ixNFqKWWuTjbYNYaxYU0/OxcNOl4AI6dKaK88Tc6kw6cBcPs5IbGHg8LbyPjgQ1HXCHgjbES2GlgCCe9aQkepo4jB3sLjxyU=
  file:
  - gapicmd_darwin_amd64
  - gapicmd_linux_amd64
  - gapicmd_windows_amd64.exe
  on:
    repo: gini/gapicmd
    tags: false
    branch: master
  skip_cleanup: true
branches:
  except:
  - "/^[0-9]/"
