language: go
go:
- '1.5'
env:
  global:
  - GAPICMD_VERSION="0.10.${TRAVIS_BUILD_NUMBER}"
  - secure: APKTTr1QkVB9znJtzR7p6ZKObPzvs8dxNUBWBF0EIoaIWRSofnMIFu9FQwoo1IQ+n+InUO3f8y6nogGFpssQCCoKB9V54cfuaqgBNRsDtf5AmxjlEM2/7Jf6RzG5dquqyBKCmKG5uqiYah9ZFbfaSxChCGwNo1a2eRJBx/Md61RlMtBNbEC8WPkmGnEgvXjlDq9z7nq52bkt5/RVf/6FS88fCsfC1hsPSaIuD+eEkQu56BBZGkroIQfMznCfl2ASPN6IuBW097EysS+kuk8oZsouLZesxs6CNUkwkMH/2QIPUB+xuOqARCm4F16UAs9W54GfjGUeS/uVa3skjq3dv3rByzliiHT9CffJHNnQ7JgM89ttYde4ze1T8maLlxCgOsUtQ20GGNq2FEFKh3Oj3oAFbPEypwDu2hr7QdubgbUMAQM169K4SsjxWnCZuUYyHMKwaFaYut8JZwQl9vox/eJ0pIovGjLoN9kOdv6OvGM8NjcVQG6J3juPSN3Tz/Udi/j6xJV5QBxvAKlsL838o2uvbgxvTvY43JHZxMkXFv5wJAYxb58bzSeHVZcpVvTZpjWnKxFNLfKqk/kP64PaZ7QSFoYzatIXgjWYzlbExUT9MZ5Yh03fQtnO75BCRGO7Hg0gbu8S1np1O4YTGS590Nvh9eYS6TqPegV3KWcMrmA=
script:
- go get github.com/mitchellh/gox
- gox -osarch="darwin/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
- gox -osarch="linux/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
- gox -osarch="windows/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
before_deploy:
- git tag ${GAPICMD_VERSION}
- git push origin --tags
deploy:
  provider: releases
  api_key:
    secure: R/3J48W6llDY/GNNPQVF7d9rPByOvxJuvu654VBQLWRWimGZarbqVHtyDEXK87sRB89g6Va76gx0SEPmp4p25fsA3Ssjfxou+LcZ0tlXp9fHZhP5qWiVJLebc1fAdYWLPmwLMJNasmSLAtWhVWbVfRLLlO13Efmh1RnVg/nstj212PB+50h/V4MFFWPGotgd/xJjm4ip6pPu7IN8OCJOG1jKid7Q5dmeP9Fc4TNI83t6CL+eZkNex0GpVUBfsrFMC+im3skmIDzc46UMckB3tZMrmhixNqs9TMxZStwunkF/Eaio0r56jKRyiXIl3A57ttybJg9Ay5agKMhI/4S6RErp89S5JBQghCGCQyofYywRJrmFR24IfIEXMcdFNP3SWWgDbdXYjUNu6z7R9wNC/AB8u6eXGjhjPnlA5HCvYrIPs+K26o2jvcC9z/uz4RUtdlbONWw6wJ4XjVuqonSWTKK60yRqhIiIu/a7yRgHhVAHLRa+8SWFFkM4S8lSoZZKiIsR6xYDdLYa5k9wcI/BFEmsGGZ5dI5J8ICWdPwpvNOwc9jslPAZ5Lb/jXGv3WXeheVxK0AIAsVvMINv9be/nVbRjvwrURyTEFZNljO4h1W5FU1Hqh2h1TTVH6XWXzh2jwLOW+7UGC8Frmrv3Oy3tRl6/l9sGyhjbfz0DxUykWo=
  file:
  - gapicmd_darwin_amd64
  - gapicmd_linux_amd64
  - gapicmd_windows_amd64.exe
  on:
    repo: gini/gapicmd
    tags: false
    branch: master
  skip_cleanup: true
branches:
  except:
  - "/^[0-9]/"
