language: go
go:
- '1.5'
env:
  global:
  - GAPICMD_VERSION="0.10.${TRAVIS_BUILD_NUMBER}"
  - secure: APKTTr1QkVB9znJtzR7p6ZKObPzvs8dxNUBWBF0EIoaIWRSofnMIFu9FQwoo1IQ+n+InUO3f8y6nogGFpssQCCoKB9V54cfuaqgBNRsDtf5AmxjlEM2/7Jf6RzG5dquqyBKCmKG5uqiYah9ZFbfaSxChCGwNo1a2eRJBx/Md61RlMtBNbEC8WPkmGnEgvXjlDq9z7nq52bkt5/RVf/6FS88fCsfC1hsPSaIuD+eEkQu56BBZGkroIQfMznCfl2ASPN6IuBW097EysS+kuk8oZsouLZesxs6CNUkwkMH/2QIPUB+xuOqARCm4F16UAs9W54GfjGUeS/uVa3skjq3dv3rByzliiHT9CffJHNnQ7JgM89ttYde4ze1T8maLlxCgOsUtQ20GGNq2FEFKh3Oj3oAFbPEypwDu2hr7QdubgbUMAQM169K4SsjxWnCZuUYyHMKwaFaYut8JZwQl9vox/eJ0pIovGjLoN9kOdv6OvGM8NjcVQG6J3juPSN3Tz/Udi/j6xJV5QBxvAKlsL838o2uvbgxvTvY43JHZxMkXFv5wJAYxb58bzSeHVZcpVvTZpjWnKxFNLfKqk/kP64PaZ7QSFoYzatIXgjWYzlbExUT9MZ5Yh03fQtnO75BCRGO7Hg0gbu8S1np1O4YTGS590Nvh9eYS6TqPegV3KWcMrmA=
  - secure: kSfrMhJzH/FuBiYC7/hr6RxRjnptV6DvNHYI6JSH2OArwYOwLS9gK4fcRk1CZb0M6TCMVHWZz79N6usjt95SQ+YBtCP+A+bBwHJiribmejjzDA/acWsWs90QM7XzIa26oP6KqqiR72k+XTNqklHVbtYv+vzqdmzsuK8Eeyx5VmmDwY/H4v1jHc1ELkBOgrnNzKHEcpI4tfQEyP1HlrR7HwOgpFOutNp97mGhlYPkuR4+NfkvOWXuLDsS8iUMY04c+MdX9hTvSpVE9EaGb5znghBmMi+oGOQQmf5f1E0yQHlEkfs6r8G66sZpf7szVhzF+CgjMauzRu92k3uJ9FSM54G9ChXaZlh/DT5Epq94z6dSd+d75UzEKErgNeAv17tDJJKD+ZqW4SfjM+lSrDuHJKpYok8EZDIOgeFGsWA2blZX1Z1VThAu2Bk11omFvUsY33fqzeLOfI4deCkuiDeq2YxCbvdsGsGqhnX4jL40+ArjgPUyQfu/niMGoGP4pTfHKt7ccP2CmrMbKQmsuiX/HSBJJ6VLkokbwcCOAQ+TSQKGg2muBAyMRVZosS+U0Bvs51QE7pheylumEmJ3AaseX8BFjem7pkuH1w+IdqgReTOP2SQxyEY1yMVf1nFghPModdBk5GeKXkJwuG9tVVqZ2B4d6xHnE7hKOP4pAkkcOmo=
script:
- go get github.com/mitchellh/gox
- gox -osarch="darwin/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
- gox -osarch="linux/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
- gox -osarch="windows/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
before_deploy:
- git tag ${GAPICMD_VERSION}
- git push --tags "https://${GH_TOKEN}@github.com/gini/gapicmd.git/" >/dev/null 2>&1
deploy:
  provider: releases
  api_key:
    secure: K0s/HVL9aDLG4fOFiQctLGbJK2tKNAmRhk4nSFyodyEL6PqJbyV8O2k8PzdUjU6N/PRcesJ9FgcICOFJ0IXI3n+Zgy3HXjpdXwXz7YvHvpOz70tP3GyeLwYEV0zZk+LD3qTCSpBjk3xLsT0TfHgrmAcOV3LKoEn1LUHgU7EEPN4tj6wH3tZdwG4XlPaMCRU0rKiGzJr5J7umSJXpm5BklpuCIRxLtX3/wLsyfszXi8D8FXl7pM3r3E7le88trBtH/U+30HHs9vT4ubL/V1Ut3l9aCWS6OkPRBsPN3GaJghSdVykQOSvc61p7OveIIXRDJt+NyFQzua2xEEgDtJSD+Kydf49wW4ch2hM/h6YBfekWLuKfsyopSjkdNkRrQMOq5gYhRIxBZgo93fO60O+zp36hS1/W82X/6zY1B3mt/N2uY+0Yfinsi0pzxmoTrcWC2BqfXUtANBhRSGjpEYd7S7jjkPKnsGVk8JRU2dp90jhJBBFvbFNUCdNo9meiyvHoXQpJ1oTS55dRfZwl+0bQprkdinAvE3gZNVMhBG3jZGzyVYO14L/qPkVb1+Zi4/o6+bnkpM0QjSKdPVDV3YUV42gPEuT9rWYOfM5ujmlELPGw54MbwodkhWDHOOZOKAZKaP4p+2Mc5T13z5sw7TVjd59jSK+9VagMY9/mjOE2kyQ=
  file:
  - gapicmd_darwin_amd64
  - gapicmd_linux_amd64
  - gapicmd_windows_amd64.exe
  on:
    repo: gini/gapicmd
    tags: false
    branch: master
  skip_cleanup: true
branches:
  except:
  - "/^[0-9]/"
