language: go
go:
- '1.5'
env:
  global:
  - GAPICMD_VERSION="0.10.${TRAVIS_BUILD_NUMBER}"
  - secure: APKTTr1QkVB9znJtzR7p6ZKObPzvs8dxNUBWBF0EIoaIWRSofnMIFu9FQwoo1IQ+n+InUO3f8y6nogGFpssQCCoKB9V54cfuaqgBNRsDtf5AmxjlEM2/7Jf6RzG5dquqyBKCmKG5uqiYah9ZFbfaSxChCGwNo1a2eRJBx/Md61RlMtBNbEC8WPkmGnEgvXjlDq9z7nq52bkt5/RVf/6FS88fCsfC1hsPSaIuD+eEkQu56BBZGkroIQfMznCfl2ASPN6IuBW097EysS+kuk8oZsouLZesxs6CNUkwkMH/2QIPUB+xuOqARCm4F16UAs9W54GfjGUeS/uVa3skjq3dv3rByzliiHT9CffJHNnQ7JgM89ttYde4ze1T8maLlxCgOsUtQ20GGNq2FEFKh3Oj3oAFbPEypwDu2hr7QdubgbUMAQM169K4SsjxWnCZuUYyHMKwaFaYut8JZwQl9vox/eJ0pIovGjLoN9kOdv6OvGM8NjcVQG6J3juPSN3Tz/Udi/j6xJV5QBxvAKlsL838o2uvbgxvTvY43JHZxMkXFv5wJAYxb58bzSeHVZcpVvTZpjWnKxFNLfKqk/kP64PaZ7QSFoYzatIXgjWYzlbExUT9MZ5Yh03fQtnO75BCRGO7Hg0gbu8S1np1O4YTGS590Nvh9eYS6TqPegV3KWcMrmA=
script:
- go get github.com/mitchellh/gox
- gox -osarch="darwin/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
- gox -osarch="linux/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
- gox -osarch="windows/amd64" -ldflags "-X main.Version ${GAPICMD_VERSION} -X main.defaultClientCredentials ${GAPICMD_DEFAULT_CREDENTIALS}" github.com/gini/gapicmd
before_deploy:
- git tag ${GAPICMD_VERSION}
- git push origin --tags
deploy:
  provider: releases
  api_key:
    secure: GXfaPDoGED3LR/ULBQg9RM6f7031Bp+pwOk23poydDlxEungMROlND/FCA57xcYUwbDZKLZk0HJKyTMoC7dROJNG8Zdl6pJmwkRoyLZQ/+b0ptfSNNp5D6QQuGPwgRCDEsF593BkStN4nfyg2OX4UxPb11FiXlsMc7r3baYaX1RQArNNuZvUErgJc7TEXRPUzg5PQGgLXAh4r0CARlLrW2CvJPy7uW1+spG8uEUe6MRLxkOcmfhzBcDDp5tUjHCg0i7Y+tOlmucdAWouPkjJUIqSIlQPBxcjzgYQ3WKDWnF3HTb7jMMAX+vwGt71tp8Tkhl3UHgrJrvlo7W12OlDqNoWDMi94BFIp7YgFtHRA8hd4D3O2dycwcItzjKEf6PGP/fHTnxHrYONMB7tAdKtgMbze2+nHY4Zt1OHOQOabTeGJN5FRxdM/XCL0PBsN2XkBAcdQ8G5rbVsNQSZQzLVXbRkbODta6GB+T277rAcPNg3dHj1HudqpkLnCr+RivakjVFrc2wOjh5hVbWXMxzf9TccW+mvChVVE8PhbrGIooxdFgNj/Cl8DueYgtJhMgSIri/UbDYAIDe52YBcQ4kvNl6hxeObXqYMZ/fA5ywi+vp7J+5gOlRWxwC3mjQOaKYGeFxrS7rDN3t5H5+YJRh6QVxMXAMGTfUGa9kbXaJsb1M=
  file:
  - gapicmd_darwin_amd64
  - gapicmd_linux_amd64
  - gapicmd_windows_amd64.exe
  skip_cleanup: true
  on:
    tags: false
    branch: master
branches:
  except:
  - "/^[0-9]/"
