language: go
go:
  - '1.4'

script:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -osarch="linux/amd64 darwin/amd64"
  - gox -osarch="darwin/amd64" github.com/gini/gapicmd
  - gox -osarch="linux/amd64" github.com/gini/gapicmd

deploy:
  provider: releases
  api_key:
    secure: "Lf80ayb44QgkewweRdVXpuFUZm0xvDPZ/HSVwlo2GBPq93RmA/5Iyz16/KUAdrRXO/Xuq6jEE84PYsZoHKHsEdrqZc/YNCpmleYo9K3abYXhD+KZmQzGMy7CTBHasRkZ65X+nSZjGeS8KysWDSszoaj4/Msr6lz1RC9TOwuq1j/w5rBue270kVwIOvJND2I3BuredeEDyAZAHu/Togn6UAED9p/8WPbSSbeYJKmrQJyM6TH50mNl5SIh6VTsVuZ8oRHXvp1p9C/X0OxOmFQjjXMuMDYa2AnugIU3dVWYlKVEjOfwZkII8Tmsk5wvyfi0vonDWEaiywnKlJl5rG6Wdw3ZuYKd9WllTqX3TpuhA+JqT0dDgUhHqfVkfoiNvXOMmsdEQtKZ7iZgVjVrIRtg9lvUmJCzbNkl0OsjWcqMneXPajASP4pO8RxOgDI1MZco5FGcl6SZ7Hq4XVpe6CUSZJsQPmeOMjRdMDETKhPn3wEF8d1ysuTSK/rGvrVmzRbFs57AGnRRgsm2go5FR8/GNihiIdpQFgutUwX+bb8ZqnB6Q1Y59iDzKkYhuPIbEfwqfPydYY3T7uqndDoKu944+i0eKp17cln6Rog+30vf8w9esct5k5Osh22KxB5bDGQI/2qD6sWI6S4JpfCZUbFJAkFvHYUxt/Xs4A/4LPX54eI="
  file:
    - gapicmd_darwin_amd64
    - gapicmd_linux_amd64
  skip_cleanup: true
  on:
    tags: true

