language: go
go:
  - '1.3'
  - '1.4'
  - '1.5'

script:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -osarch="linux/amd64 darwin/amd64"
  - gox -osarch="darwin/amd64" github.com/gini/gapicmd
  - gox -osarch="linux/amd64" github.com/gini/gapicmd

deploy:
  provider: releases
  api_key:
    secure: "QRCJ11jlFSJA9Bl8xPO6mtjaKjhppdLGKIY0/73JH/5Cw3qUcrs78UX8GgEnq7DeD/z1Phg2IH4Wuu/AoxWeuEzjGr12NNTbFFtTcmw9y56xK6awrE3eZ48Csvs2AQUnZMpK9whPpWLTaT/TTWTVh6yKGfDRM/e878kcOLgXparFhhfHfKKd2ftkfd5BRMVMu30jF797fshrnfoa/pt76Te9QYI7nzos4+eXBlGAM24u9pMYrDwjXX1nhjcseZoVHMciRO7KR+yTxIkhPe1tBE5Q/YTHlDKI4BJnh5aalzo+kveUcaK0B0V0bGl6Wy2jm6SFfWuE8puZ5eueRP6teI3gTvoZvLD3xFhioAFgyGBxGIeqE2IwqTZxay8FTyBonEpwkdXmGulfVS8kkLW3oEa736R7nZl132JSlD/rZMNu4EnjCiqSV1UCydtoXIRFjDj/zGgV4Ymj6c8SKFvNBGKsE+qL8of6wxXHpBcMxNoD+PpHwnyX+0FRzj5s6xCV4fr0zQXJFEF2DY2t8Nlkzye7c3dDpDw2KAPHZuRyMsoCiFzG1rMdv3ACQ52/4xZ1Sinuub52oc1PZsT2NHH3ldSdNJLdU0BitxJ3WYGu7S/zCUCBX2Clfhs3VuRRkTErvu5yFtZ+keNsrmyf27eWUcGaYNKapfKOH4ceM21AIQI="
  file:
    - gapicmd_darwin_amd64
    - gapicmd_linux_amd64
  skip_cleanup: true
  on:
    tags: true

